# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='\u042d\u043b. \u043f\u043e\u0447\u0442\u0430:')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, verbose_name='\u0412\u0430\u0448 email:')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f:')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='T\u0435\u043b\u0435\u0444\u043e\u043d:')),
                ('address', models.CharField(max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441:')),
                ('postal_code', models.CharField(blank=True, default=None, max_length=20, null=True, validators=[utils.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434:')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434:')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f:')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='T\u0435\u043b\u0435\u0444\u043e\u043d:')),
                ('address', models.CharField(max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441:')),
                ('postal_code', models.CharField(blank=True, default=None, max_length=20, null=True, validators=[utils.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434:')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041b\u043e\u0433\u0438\u043d:')),
            ],
        ),
    ]
