# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u0412\u0430\u0448 email'),
        ),
    ]
