# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 09:44
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171121_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='guest_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+71234567890', max_length=128),
        ),
    ]
