# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180323_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='woked_products',
            field=models.BooleanField(default=False),
        ),
    ]
