# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 09:46
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guestemail_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='guest_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+71234567890', max_length=128, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043b\u0435\u0444\u043e\u043d:'),
        ),
    ]
