# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='email',
            field=models.EmailField(default='vasia@yandex.ru', max_length=254, verbose_name='\u0412\u0430\u0448 email:'),
        ),
    ]
