# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171222_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u0412\u0430\u0448 email:'),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='guest_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043b\u0435\u0444\u043e\u043d:'),
        ),
    ]
