# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180115_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043b\u0435\u0444\u043e\u043d:'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, validators=[utils.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434'),
        ),
    ]
