# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180123_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='\u041c\u043e\u0441\u043a\u0432\u0430', max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='\u0420\u0443\u0441\u0442\u0430\u043c \u0420\u0443\u0441\u0442\u0430\u043c\u043e\u0432', max_length=255, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+81234567890', max_length=128, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043b\u0435\u0444\u043e\u043d:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, validators=[utils.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434'),
        ),
    ]
