# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u0423\u043f\u0430\u043a\u043e\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='product',
            name='typeprice',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='\u0417\u0430 \u043a\u0430\u043a\u043e\u0435 \u043a\u043e\u043b-\u0432\u043e \u0443\u043a\u0430\u0437\u0430\u043d\u0430 \u0446\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='\u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'),
        ),
    ]
