# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180221_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stack',
            field=models.BooleanField(db_index=True, default=True, verbose_name='\u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=True, verbose_name='\u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 "\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b"'),
        ),
    ]
