# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180321_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stack',
        ),
    ]
