# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180321_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='\u0432 \u0440\u0430\u0437\u0434\u0435\u043b "\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b"'),
        ),
    ]
