# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20180115_1929'),
        ('shop', '0004_auto_20171227_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='000', max_length=32, verbose_name='\u041a\u043b\u044e\u0447 \u0442\u0435\u043a\u0443\u0449\u0435\u0439 \u0441\u0435\u0441\u0441\u0438\u0438')),
                ('shipping', models.CharField(choices=[('\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u043e\u0439', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0432 \u043f\u0440\u0435\u0434\u0435\u043b\u0430\u0445 \u0412\u043e\u0441\u0442\u043e\u0447\u043d\u043e\u0433\u043e \u041e\u043a\u0440\u0443\u0433\u0430 \u041c\u043e\u0441\u043a\u0432\u044b'), ('\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437', '\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437')], default='\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u043e\u0439', max_length=50, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438:')),
                ('shipping_state', models.BooleanField(default=True, verbose_name='\u041d\u0443\u0436\u043d\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430')),
                ('address', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('postal_code', models.CharField(blank=True, default=None, max_length=20, null=True, validators=[orders.models.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d')),
                ('guest_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GuestEmail', verbose_name='Email')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
    ]
