# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171220_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, validators=[orders.models.postal_code_validator], verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u043a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('0', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0432 \u043f\u0440\u0435\u0434\u0435\u043b\u0430\u0445 \u0412\u043e\u0441\u0442\u043e\u0447\u043d\u043e\u0433\u043e \u041e\u043a\u0440\u0443\u0433\u0430 \u041c\u043e\u0441\u043a\u0432\u044b'), ('1', '\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437')], default='0', max_length=1, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438:'),
        ),
    ]
