# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20171224_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u043e\u0439', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0432 \u043f\u0440\u0435\u0434\u0435\u043b\u0430\u0445 \u0412\u043e\u0441\u0442\u043e\u0447\u043d\u043e\u0433\u043e \u041e\u043a\u0440\u0443\u0433\u0430 \u041c\u043e\u0441\u043a\u0432\u044b'), ('\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437', '\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437')], default='\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u043e\u0439', max_length=50, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438:'),
        ),
    ]
