# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171227_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.BooleanField(default=True, verbose_name='\u041d\u0443\u0436\u043d\u0430 \u043b\u0438 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430'),
        ),
    ]
