# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.BooleanField(default=True, verbose_name='\u041d\u0443\u0436\u043d\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430'),
        ),
    ]
